export const FETCH_ACCESSORIES = 'FETCH_ACCESSORIES';
export const FETCH_ACCESSORIES_SUCCESS = 'FETCH_ACCESSORIES_SUCCESS';
/* Sinh */
export const UPDATE_LIST_ACCESSORIES = 'UPDATE_LIST_ACCESSORIES'; 
export const UPDATE_LIST_ACCESSORIES_SUCCESS = 'UPDATE_LIST_ACCESSORIES_SUCCESS'; 
export const SELECT_ACCESSORIES_ITEM = 'SELECT_ACCESSORIES_ITEM'; 
/* Sinh */
export const FETCH_ACCESSORIES_FAIL = 'FETCH_ACCESSORIES_FAIL';