export const FETCH_ACCESSORY = 'FETCH_ACCESSORY';
export const FETCH_ACCESSORY_SUCCESS = 'FETCH_ACCESSORY_SUCCESS';
export const FETCH_ACCESSORY_FAIL = 'FETCH_ACCESSORY_FAIL';

export const CREATE_ACCESSORY = "CREATE_ACCESSORY";
export const CREATE_ACCESSORY_SUCCESS = "CREATE_ACCESSORY_SUCCESS";
export const CREATE_ACCESSORY_FAIL = "CREATE_ACCESSORY_FAIL";

export const UPDATE_ACCESSORY = "UPDATE_ACCESSORY";
export const UPDATE_ACCESSORY_SUCCESS = "UPDATE_ACCESSORY_SUCCESS";
export const UPDATE_ACCESSORY_FAIL = "UPDATE_ACCESSORY_FAIL";

export const DELETE_ACCESSORY = "DELETE_ACCESSORY";
export const DELETE_ACCESSORY_SUCCESS = "DELETE_ACCESSORY_SUCCESS";
export const DELETE_ACCESSORY_FAIL = "DELETE_ACCESSORY_FAIL";