export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILED = "FETCH_EMPLOYEE_FAILED";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILED = "CREATE_EMPLOYEE_FAILED";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILED = "UPDATE_EMPLOYEE_FAILED";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";
export const GET_ITEM_EMPLOYEE = "GET_EMPLOYEE_ITEM";
export const GET_ITEM_SUCCESS = "GET_EMPLOYEE_ITEM_SUCCESS";
export const GET_ITEM_FAILED = "GET_EMPLOYEE_ITEM_FAILED";
export const CHANGE_PASSWORD_USER= "CHANGE_PASSWORD_USER";
export const CHANGE_PASSWORD_USER_SUCCESS= "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_USER_FAILED= "CHANGE_PASSWORD_FAILED";
export const GET_MAINTENANCECARD_BY_USER_ID= "GET_MAINTENANCECARD_BY_USER_ID";
export const GET_MAINTENANCECARD_BY_USER_ID_SUCCESS= "GET_MAINTENANCECARD_BY_SUCCESS";
export const GET_MAINTENANCECARD_BY_USER_ID_FAILED= "GET_MAINTENANCECARD_BY_FAILED";



